language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true
install:
  - 'pip install pipenv'
  - 'pipenv install --sytem --deploy'
script: 
  - 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'